export const divindadesData = [
  { value: 'aharadak', nome: 'Aharadak' },
  { value: 'allihanna', nome: 'Allihanna' },
  { value: 'arsenal', nome: 'Arsenal' },
  { value: 'azgher', nome: 'Azgher' },
  { value: 'hyninn', nome: 'Hyninn' },
  { value: 'kallyadranoch', nome: 'Kallyadranoch' },
  { value: 'khalmyr', nome: 'Khalmyr' },
  { value: 'lena', nome: 'Lena' },
  { value: 'lin-wu', nome: 'Lin-wu' },
  { value: 'marah', nome: 'Marah' },
  { value: 'megalokk', nome: 'Megalokk' },
  { value: 'nimb', nome: 'Nimb' },
  { value: 'oceano', nome: 'Oceano' },
  { value: 'sszzaas', nome: 'Sszzaas' },
  { value: 'tanna-toh', nome: 'Tanna-Toh' },
  { value: 'tenebra', nome: 'Tenebra' },
  { value: 'thwor', nome: 'Thwor' },
  { value: 'thyatis', nome: 'Thyatis' },
  { value: 'valkaria', nome: 'Valkaria' },
  { value: 'wynna', nome: 'Wynna' }
]
